### ISSUE TITLE
Optimising compile time for large global arrays

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/pawn#168]
Disclaimer: I'm essentially an uneducated idiot when it comes to compilers!

In my gamemode (and many others, I assume), there are a few large global array allocations (in my case, it's a survival game where items spawn all over the map - there can be anywhere between 10 and 20 thousand items in the game world at any time, hence the large arrays to store that data).

I chatted a bit on the SA:MP discord about this and learnt that global arrays are zero-filled on compilation and this is probably what causes the slower compile times.

Is there *any* way to optimise this? Buffering writes to the output stream? I seem to remember y_malloc did some magic to utilise large memory areas but I forgot how.

It's just a quality-of-life thing really, my compile-times are around 60 seconds with my "minimal" flag set that makes a few larger arrays smaller, and around 110 seconds when doing a full production compile. Even getting that time down by 10 seconds would be great. If I knew more about the compiler, I'd probably look into implementing this myself so I'm asking here for some input!

**Comment by maddinat0r** [comment]
Arrays have to be filled with something, as their contents are written into the AMX file. I think there is no way to improve compilation speed here. 

However, I actually managed to improve overall compile speed (I think) by optimizing the internal file write function.
This script
```pawn
#include <a_samp>

main() {}

new bigarray[10000000];

public OnGameModeInit()
{
    bigarray[2] = 3;
    SendClientMessage(bigarray[2], -1, "hi");
	return 1;
}
```
took 4.676 seconds to compile with full debug information (d3) on the original compiler shipped with the SA-MP server package, while on mine it only took 1.4 seconds with identical compiler arguments. The disassembly output is the same, so I guess its working. No guarantees here though.
Here's the patch for my changes: 
```patch
From e578b3c228550addf1b6f8ed8487151f6168f3ee Mon Sep 17 00:00:00 2001
From: Alex Martin <maddin4t0r@gmail.com>
Date: Mon, 1 May 2017 19:27:41 +0200
Subject: [PATCH] optimize write op

---
 source/compiler/sc7.c | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/source/compiler/sc7.c b/source/compiler/sc7.c
index 5981efc..253c7ce 100644
--- a/source/compiler/sc7.c
+++ b/source/compiler/sc7.c
@@ -1368,6 +1368,7 @@ static int filewrite(char *str)
 SC_FUNC void stgwrite(const char *st)
 {
   int len;
+  int st_len;
 
   if (staging) {
     assert(stgidx==0 || stgbuf!=NULL);  /* staging buffer must be valid if there is (apparently) something in it */
@@ -1381,9 +1382,10 @@ SC_FUNC void stgwrite(const char *st)
     stgbuf[stgidx++]='\0';
   } else {
     len=(stgbuf!=NULL) ? strlen(stgbuf) : 0;
-    CHECK_STGBUFFER(len+strlen(st)+1);
-    strcat(stgbuf,st);
-    len=strlen(stgbuf);
+   st_len=strlen(st);
+   CHECK_STGBUFFER(len+st_len+1);
+   memcpy(stgbuf + len, st, st_len + 1);
+    len=len+st_len;
     if (len>0 && stgbuf[len-1]=='\n') {
       filewrite(stgbuf);
       stgbuf[0]='\0';
-- 
2.10.2.windows.1

```

**Comment by Southclaws** [comment]
That's actually sort of what I had in mind, I was poking around at the `stgwrite` calls and wondered if messing with the buffer or file writes would change anything.

I'll give that a try on my monster of a codebase and see if it speeds it up in any way, thanks!

**Comment by justnonamenoname** [comment]
There is already solution, but not open source

By unknown reason Zeex ignore me

gta-samp.com/files/pawncc.exe

https://github.com/Zeex/pawn/issues/147

**Comment by Southclaws** [comment]
One of the reasons I use this compiler is due to the Linux capability to
automate builds. I think forking off into multiple compilers is bad for
everybody so open sourcing that to GitHub and sorting out a merge of both
via pull requests would probably be the best course of action.

Barnaby Keene | southcla.ws

**Comment by Y-Less** [comment]
Replying to the deleted post: a closed-source solution is not a solution at all.  I also doubt @Zeex is ignoring you, he just is not very active, but I'm sure if you made a pull request he'd at least review it (eventually, again he is not very active, but pops up randomly).

**Comment by Jeroen52** [comment]
I'm actually using Zeex's compiler to automatically build any code that I commit.

![chrome_2017-05-12_17-06-30](https://cloud.githubusercontent.com/assets/2915526/26004446/335f2150-3736-11e7-844f-b0033a537064.png)

However, I am using the fast Russian compiler for when I need to debug code, because it is so fast.

It'd be very benefitial for everyone if there were no forks (other than identical mirrors) and that everyone was contributing to the same compiler.

**Comment by antoine98** [comment]
@Jeroen52 Good afternoon, Could you share how to use pipelines with pawn and especially .yml configuration.
Thanks.

**Comment by Jeroen52** [comment]
@antoine98 If I am correct this is the Dockerfile of the Docker container I'm using to build the code.
```docker
FROM centos:7

MAINTAINER jeroen@jeroendeneef.com

ENV VERSION 3.10.2
ENV PAWNCFOLDER pawnc-$VERSION-linux
ENV PAWNCTARBALL $PAWNCFOLDER.tar.gz


ADD https://github.com/Zeex/pawn/releases/download/v$VERSION/$PAWNCTARBALL \
	/$PAWNCTARBALL

LABEL	name="Zeex's pawn compiler" \
		vendor="Zeex" \
		license="zLib/libpng" \
		build-date="20160304"

RUN yum -y install \
		deltarpm; \
	yum -y groupinstall \
		'Development Tools'; \
	yum -y install \
		kernel-devel git glibc.i686 \
		libuuid libuuid-devel openssl \
		openssl-devel wget; \
	yum -y clean \
		all

RUN tar -xvf $PAWNCTARBALL; \
	rm $PAWNCTARBALL; \
	mv $PAWNCFOLDER/lib/libpawnc.so lib/; \
	mv $PAWNCFOLDER/bin/pawndisasm bin/; \
	mv $PAWNCFOLDER/bin/pawncc bin/; \
	rm -rf $PAWNCFOLDER

```

This is the YML file.

```yml
image: pawnc:latest
stages:
- prereq
- autogen
- build

build:git-hash:linux:
    stage: prereq
    before_script:
    - git submodule sync
    - git submodule update --init
    script: 
    - cd pawno/include/samp-git-hash
    - make
    tags:
    - linux
    - git
    - pawn
    - libpawnc
    - pawncc
    - pawndisasm

autogen:git-hash:linux:
    stage: autogen
    script:
    - cd pawno/include/samp-git-hash
    - chmod +x git-hash
    - rm -rf .git
    - ./git-hash
    dependencies:
    - build:git-hash:linux
    tags:
    - linux
    - git
    - pawn
    - libpawnc
    - pawncc
    - pawndisasm

build:gamemode:linux:
    stage: build
    script: 
    - cd gamemodes
    - pawncc "-;+" "-(+" -i:../pawno/include SFCRRPG.pwn -Z
    dependencies:
    - autogen:git-hash:linux
    tags:
    - linux
    - git
    - pawn
    - libpawnc
    - pawncc
    - pawndisasm
    artifacts:
        paths:
        - gamemodes/SFCRRPG.amx
        expire_in: 12 hours

```
